/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import Derivadas.Derivadas;
import Derivadas.Escolha;
/**
 *
 * @author danie
 */
public class TelaEscolhaDerivada extends javax.swing.JFrame {
    //Objetos das Classes
    Derivadas derivada = new Derivadas();
    Escolha escolha = new Escolha();
    /**
     * Creates new form TelaEscolhaDerivada
     */
    public TelaEscolhaDerivada() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonDevExplicita12 = new javax.swing.JButton();
        jButtonDevImplicita = new javax.swing.JButton();
        jButtonDevCompostas = new javax.swing.JButton();
        jButtonDevParciais = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha a Derivada");

        jButtonDevExplicita12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDevExplicita12.setText("Derivadas Explicitas");
        jButtonDevExplicita12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevExplicita12ActionPerformed(evt);
            }
        });

        jButtonDevImplicita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDevImplicita.setText("Derivadas Implícitas");
        jButtonDevImplicita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevImplicitaActionPerformed(evt);
            }
        });

        jButtonDevCompostas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDevCompostas.setText("Derivadas Compostas");
        jButtonDevCompostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevCompostasActionPerformed(evt);
            }
        });

        jButtonDevParciais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDevParciais.setText("Derivadas Parciais");
        jButtonDevParciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevParciaisActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonDevExplicita12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDevImplicita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDevCompostas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVoltar)
                            .addComponent(jButtonDevParciais, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jButtonDevExplicita12)
                .addGap(18, 18, 18)
                .addComponent(jButtonDevImplicita)
                .addGap(18, 18, 18)
                .addComponent(jButtonDevCompostas)
                .addGap(18, 18, 18)
                .addComponent(jButtonDevParciais)
                .addGap(67, 67, 67)
                .addComponent(jButtonVoltar)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDevExplicita12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevExplicita12ActionPerformed
        Escolha.escolhaDerivada = "DerivadaExplicita";
        TelaDerivada janelaDerivada = new TelaDerivada();
        janelaDerivada.setVisible(true);
        dispose(); //Fecha a janela atual
    }//GEN-LAST:event_jButtonDevExplicita12ActionPerformed

    private void jButtonDevImplicitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevImplicitaActionPerformed
        Escolha.escolhaDerivada = "DerivadaImplicita";
        TelaDerivada janelaDerivada = new TelaDerivada();
        janelaDerivada.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDevImplicitaActionPerformed

    private void jButtonDevCompostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevCompostasActionPerformed
        Escolha.escolhaDerivada = "DerivadaComposta";
        TelaDerivada janelaDerivada = new TelaDerivada();
        janelaDerivada.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDevCompostasActionPerformed

    private void jButtonDevParciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevParciaisActionPerformed
        Escolha.escolhaDerivada = "DerivadaParcial";
        TelaDerivada janelaDerivada = new TelaDerivada();
        janelaDerivada.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDevParciaisActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaEscolha janelaEscolha = new TelaEscolha();
        dispose();
        janelaEscolha.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscolhaDerivada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDevCompostas;
    private javax.swing.JButton jButtonDevExplicita12;
    private javax.swing.JButton jButtonDevImplicita;
    private javax.swing.JButton jButtonDevParciais;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
