/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import Derivadas.Derivadas;
import Derivadas.Escolha;
/**
 *
 * @author Aluno
 */
public class TelaDerivada extends javax.swing.JFrame {
    //Objeto das Classes
    Derivadas derivada = new Derivadas();
    /**
     * Creates new form TelaDerivada
     */
    public TelaDerivada() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Caso escolha, derivada Implicita
        if(!Escolha.escolhaDerivada.equals("DerivadaImplicita")){
            jTextFieldVariavelY.setEnabled(false);
        }
        
        setTitle(Escolha.escolhaDerivada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog1 = new javax.swing.JDialog();
        jTextFieldCampo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxOrdem1 = new javax.swing.JCheckBox();
        jCheckBoxOrdem2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonNumero1 = new javax.swing.JButton();
        jButtonNumero4 = new javax.swing.JButton();
        jButtonNumero7 = new javax.swing.JButton();
        jButtonExpoente = new javax.swing.JButton();
        jButtonNumero2 = new javax.swing.JButton();
        jButtonNumero5 = new javax.swing.JButton();
        jButtonNumero0 = new javax.swing.JButton();
        jButtonNumero9 = new javax.swing.JButton();
        jButtonNumero6 = new javax.swing.JButton();
        jButtonNumero3 = new javax.swing.JButton();
        jButtonNumero8 = new javax.swing.JButton();
        jButtonSinaligual = new javax.swing.JButton();
        jButtonSoma = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonRaizQuadrada = new javax.swing.JButton();
        jButtonParentesesEsq = new javax.swing.JButton();
        jButtonParentesesDir = new javax.swing.JButton();
        jButtonVariavelX = new javax.swing.JButton();
        jButtonVariavelY = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonSeno = new javax.swing.JButton();
        jButtonCosseno = new javax.swing.JButton();
        jButtonC_LimparTela = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldVariavelX = new javax.swing.JTextField();
        jTextFieldResultado = new javax.swing.JTextField();
        jTextFieldVariavelY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldCampo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTextFieldCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoActionPerformed(evt);
            }
        });

        jLabel1.setText("f(x)=");

        jCheckBoxOrdem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxOrdem1.setText("1º ORDEM");
        jCheckBoxOrdem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOrdem1ActionPerformed(evt);
            }
        });

        jCheckBoxOrdem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxOrdem2.setText("2º ORDEM");
        jCheckBoxOrdem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOrdem2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Insira a função:");

        jButtonNumero1.setText("1");
        jButtonNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero1ActionPerformed(evt);
            }
        });

        jButtonNumero4.setText("4");
        jButtonNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero4ActionPerformed(evt);
            }
        });

        jButtonNumero7.setText("7");
        jButtonNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero7ActionPerformed(evt);
            }
        });

        jButtonExpoente.setText("^");
        jButtonExpoente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpoenteActionPerformed(evt);
            }
        });

        jButtonNumero2.setText("2");
        jButtonNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero2ActionPerformed(evt);
            }
        });

        jButtonNumero5.setText("5");
        jButtonNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero5ActionPerformed(evt);
            }
        });

        jButtonNumero0.setText("0");
        jButtonNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero0ActionPerformed(evt);
            }
        });

        jButtonNumero9.setText("9");
        jButtonNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero9ActionPerformed(evt);
            }
        });

        jButtonNumero6.setText("6");
        jButtonNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero6ActionPerformed(evt);
            }
        });

        jButtonNumero3.setText("3");
        jButtonNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero3ActionPerformed(evt);
            }
        });

        jButtonNumero8.setText("8");
        jButtonNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero8ActionPerformed(evt);
            }
        });

        jButtonSinaligual.setText("=");
        jButtonSinaligual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinaligualActionPerformed(evt);
            }
        });

        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jButtonSubtracao.setText("-");
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });

        jButtonMultiplicacao.setText("*");
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonDivisao.setText("/");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButtonRaizQuadrada.setText("√");
        jButtonRaizQuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizQuadradaActionPerformed(evt);
            }
        });

        jButtonParentesesEsq.setText("(");
        jButtonParentesesEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParentesesEsqActionPerformed(evt);
            }
        });

        jButtonParentesesDir.setText(")");
        jButtonParentesesDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParentesesDirActionPerformed(evt);
            }
        });

        jButtonVariavelX.setText("x");
        jButtonVariavelX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVariavelXActionPerformed(evt);
            }
        });

        jButtonVariavelY.setText("y");
        jButtonVariavelY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVariavelYActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Derivadas");

        jButtonSeno.setText("sin");
        jButtonSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSenoActionPerformed(evt);
            }
        });

        jButtonCosseno.setText("cos");
        jButtonCosseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCossenoActionPerformed(evt);
            }
        });

        jButtonC_LimparTela.setText("C");
        jButtonC_LimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC_LimparTelaActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel4.setText("Digite a variável:");

        jTextFieldVariavelX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVariavelXXActionPerformed(evt);
            }
        });

        jTextFieldResultado.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTextFieldResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultadoActionPerformed(evt);
            }
        });

        jTextFieldVariavelY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVariavelYActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxOrdem1)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxOrdem2))
                            .addComponent(jTextFieldCampo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldResultado, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButtonVoltar)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jButtonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonExpoente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jButtonC_LimparTela, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonSinaligual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jButtonVariavelX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonCosseno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(21, 21, 21)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldVariavelX, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldVariavelY, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonRaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonParentesesEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonParentesesDir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonVariavelY, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 12, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBoxOrdem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxOrdem2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVariavelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVariavelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonParentesesEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonParentesesDir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVariavelY, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExpoente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCosseno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonC_LimparTela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSinaligual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonVariavelX, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSeno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jButtonVoltar)
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxOrdem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOrdem1ActionPerformed
        if(jCheckBoxOrdem1.isSelected()){
            jCheckBoxOrdem2.setEnabled(false);
        }else{
            jCheckBoxOrdem2.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBoxOrdem1ActionPerformed

    private void jCheckBoxOrdem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOrdem2ActionPerformed
        if(jCheckBoxOrdem2.isSelected()){
            jCheckBoxOrdem1.setEnabled(false);
        }else{
            jCheckBoxOrdem1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBoxOrdem2ActionPerformed

    private void jButtonNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero4ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "4" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero4ActionPerformed

    private void jButtonNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero2ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "2" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero2ActionPerformed

    private void jButtonNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero6ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "6" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero6ActionPerformed

    private void jButtonNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero7ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "7" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero7ActionPerformed

    private void jButtonVariavelXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVariavelXActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "x" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonVariavelXActionPerformed

    private void jButtonCossenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCossenoActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "cos()" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonCossenoActionPerformed

    private void jButtonNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero1ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "1" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero1ActionPerformed

    private void jButtonNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero5ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "5" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero5ActionPerformed

    private void jButtonNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero8ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "8" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero8ActionPerformed

    private void jButtonNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero9ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "9" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero9ActionPerformed

    private void jButtonNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero0ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "0" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero0ActionPerformed

    private void jButtonSinaligualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinaligualActionPerformed
        //Armazena a escolha do usuário feita na interface anterior.
        String escolhaDerivada = Escolha.escolhaDerivada;
        
        //Verifica qual a escolha do usuário e qual checkbox está ativada
        if(escolhaDerivada.equals("DerivadaExplicita") && jCheckBoxOrdem1.isSelected()){ //Funciona, implementar pro restante
            String expressao = jTextFieldCampo.getText();
            String variavel = jTextFieldVariavelX.getText();
            if(jTextFieldCampo.getText().isEmpty() || jTextFieldVariavelX.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.calculaDerivada(expressao, variavel));
            }
        }
        
        else if(escolhaDerivada.equals("DerivadaExplicita") && jCheckBoxOrdem2.isSelected()){
            String expressao = jTextFieldCampo.getText();
            String variavel = jTextFieldVariavelX.getText();
            if(jTextFieldCampo.getText().isEmpty() || jTextFieldVariavelX.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.calculaDerivadaSegunda(expressao, variavel));
            }
        }
        
        else if(escolhaDerivada.equals("DerivadaImplicita") && jCheckBoxOrdem1.isSelected()){
            String expressao = jTextFieldCampo.getText();
            String variavelX = jTextFieldVariavelX.getText();
            String variavelY = jTextFieldVariavelY.getText();
            if(jTextFieldCampo.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.derivadaImplicita(expressao, variavelX, variavelY));
            }
        }
        
        else if(escolhaDerivada.equals("DerivadaImplicita") && jCheckBoxOrdem2.isSelected()){
            String expressao = jTextFieldCampo.getText();
            String variavelX = jTextFieldVariavelX.getText();
            String variavelY = jTextFieldVariavelY.getText();            
            if(jTextFieldCampo.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.segundaDerivadaImplicita(expressao, variavelX, variavelY));
            }
        }
        
        else if(escolhaDerivada.equals("DerivadaComposta") && jCheckBoxOrdem1.isSelected()){
            String expressao = jTextFieldCampo.getText();
            String variavel = jTextFieldVariavelX.getText();
            if(jTextFieldCampo.getText().isEmpty() || jTextFieldVariavelX.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.calculaDerivada(expressao, variavel));
            }
        }
        
        else if(escolhaDerivada.equals("DerivadaComposta") && jCheckBoxOrdem2.isSelected()){
            String expressao = jTextFieldCampo.getText();
            String variavel = jTextFieldVariavelX.getText();
            if(jTextFieldCampo.getText().isEmpty() || jTextFieldVariavelX.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.calculaDerivadaSegunda(expressao, variavel));
            }
        }
        
        else if(escolhaDerivada.equals("DerivadaParcial") && jCheckBoxOrdem1.isSelected()){
            String expressao = jTextFieldCampo.getText();
            String variavel = jTextFieldVariavelX.getText();
            if(jTextFieldCampo.getText().isEmpty() || jTextFieldVariavelX.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.derivadaParcial(expressao, variavel));
            }
        }
        
        else if(escolhaDerivada.equals("DerivadaParcial") && jCheckBoxOrdem2.isSelected()){
            String expressao = jTextFieldCampo.getText();
            String variavel = jTextFieldVariavelX.getText();
            if(jTextFieldCampo.getText().isEmpty() || jTextFieldVariavelX.getText().isEmpty()){
                jTextFieldCampo.setText("Erro, preenchimento obrigatório");
            }else{
                jTextFieldResultado.setText(derivada.derivadaParcialSegunda(expressao, variavel));
            }
        }
    }//GEN-LAST:event_jButtonSinaligualActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "+" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonRaizQuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizQuadradaActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "sqrt()" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonRaizQuadradaActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "-" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonSubtracaoActionPerformed

    private void jButtonParentesesEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParentesesEsqActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "(" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonParentesesEsqActionPerformed

    private void jButtonParentesesDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParentesesDirActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + ")" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonParentesesDirActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "*" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButtonC_LimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonC_LimparTelaActionPerformed
        jTextFieldCampo.setText("");
    }//GEN-LAST:event_jButtonC_LimparTelaActionPerformed

    private void jButtonExpoenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpoenteActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "^" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonExpoenteActionPerformed

    private void jButtonNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero3ActionPerformed
        int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "3" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonNumero3ActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
                int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "/" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonVariavelYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVariavelYActionPerformed
                int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "y" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonVariavelYActionPerformed

    private void jButtonSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSenoActionPerformed
                int posicaoTexto = jTextFieldCampo.getCaretPosition();
        String textoAtual = jTextFieldCampo.getText();
        String novoTexto = textoAtual.substring(0, posicaoTexto) + "sin()" + textoAtual.substring(posicaoTexto);
        jTextFieldCampo.setText(novoTexto);
        jTextFieldCampo.setCaretPosition(posicaoTexto + 1);
    }//GEN-LAST:event_jButtonSenoActionPerformed

    private void jTextFieldCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoActionPerformed
        
    }//GEN-LAST:event_jTextFieldCampoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaEscolhaDerivada interfaceEscolha = new TelaEscolhaDerivada();
        dispose();
        interfaceEscolha.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldVariavelXXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVariavelXXActionPerformed

    }//GEN-LAST:event_jTextFieldVariavelXXActionPerformed

    private void jTextFieldResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultadoActionPerformed

    private void jTextFieldVariavelYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVariavelYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVariavelYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDerivada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonC_LimparTela;
    private javax.swing.JButton jButtonCosseno;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonExpoente;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonNumero0;
    private javax.swing.JButton jButtonNumero1;
    private javax.swing.JButton jButtonNumero2;
    private javax.swing.JButton jButtonNumero3;
    private javax.swing.JButton jButtonNumero4;
    private javax.swing.JButton jButtonNumero5;
    private javax.swing.JButton jButtonNumero6;
    private javax.swing.JButton jButtonNumero7;
    private javax.swing.JButton jButtonNumero8;
    private javax.swing.JButton jButtonNumero9;
    private javax.swing.JButton jButtonParentesesDir;
    private javax.swing.JButton jButtonParentesesEsq;
    private javax.swing.JButton jButtonRaizQuadrada;
    private javax.swing.JButton jButtonSeno;
    private javax.swing.JButton jButtonSinaligual;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JButton jButtonVariavelX;
    private javax.swing.JButton jButtonVariavelY;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxOrdem1;
    private javax.swing.JCheckBox jCheckBoxOrdem2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextFieldCampo;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldVariavelX;
    private javax.swing.JTextField jTextFieldVariavelY;
    // End of variables declaration//GEN-END:variables
}
